In [22]:
import pandas as pd

In [24]:
ruta_excel = r"C:\Users\cecir\OneDrive\Documentos\Simulacion\CAlcular pi con montecarlo\PROYECCION ESTIMACION alumnos.xlsx"

Datos_de_educacion_df = pd.read_excel(ruta_excel)

Datos_de_educacion_df.head(20)

,Nivel Educativo,Alumnos 18-19,Alumnos 19-20,Alumnos 20-21,Alumnos 21-22,Alumnos 22-23,Alumnos 23-24,Alumnos 24-25,Alumnos 25-26,Alumnos 26-27,Alumnos 27-28,Alumnos 28-29,Alumnos 29-30
0,INICIAL ESCOLARIZADO,15635.0,9692.0,7151.0,8272.0,9227.0,9547,NaN,NaN,NaN,NaN,NaN,NaN
1,INICIAL NO ESCOLARIZADA,8537.0,9440.0,5271.0,4897.0,5147.0,1604,NaN,NaN,NaN,NaN,NaN,NaN
2,ESPECIAL CAM,3371.0,3511.0,3179.0,3303.0,3214.0,3317,NaN,NaN,NaN,NaN,NaN,NaN
3,ESPECIAL USAER,37292.0,37470.0,32760.0,33562.0,38049.0,37882,NaN,NaN,NaN,NaN,NaN,NaN
4,PREESCOLAR GENERAL,121192.0,125965.0,126992.0,124747.0,126821.0,125557,NaN,NaN,NaN,NaN,NaN,NaN
5,PREESCOLAR COMUNITARIO,2426.0,2626.0,2848.0,3000.0,3114.0,2918,NaN,NaN,NaN,NaN,NaN,NaN
6,PRIMARIA GENERAL,336772.0,338239.0,328740.0,323590.0,326842.0,334829,NaN,NaN,NaN,NaN,NaN,NaN
7,PRIMARIA COMUNITARIO,341.0,334.0,335.0,357.0,329.0,347,NaN,NaN,NaN,NaN,NaN,NaN
8,SECUNDARIAS,154055.0,154209.0,157053.0,156921.0,153835.0,155030,NaN,NaN,NaN,NaN,NaN,NaN
9,SECUNDARIA COMUNITARIO,127.0,134.0,133.0,131.0,128.0,226,NaN,NaN,NaN,NaN,NaN,NaN
10,FORMACIÃ“N PARA EL TRABAJO,53863.0,46860.0,39298.0,24604.0,47609.0,43698,NaN,NaN,NaN,NaN,NaN,NaN
11,EDUCACI&Oacute;N MEDIA SUPERIOR,141259.0,137212.0,126403.0,122898.0,132873.0,136621,NaN,NaN,NaN,NaN,NaN,NaN
12,EDUCACI&Oacute;N SUPERIOR,116016.0,124677.0,131823.0,131604.0,132973.0,141192,NaN,NaN,NaN,NaN,NaN,NaN
13,EDUCACION PARA ADULTOS,68581.0,63279.0,35372.0,46742.0,49334.0,55982,NaN,NaN,NaN,NaN,NaN,NaN
14,INICIAL CCAPI,NaN,NaN,NaN,177.0,419.0,671,NaN,NaN,NaN,NaN,NaN,NaN
15,INICIAL COMUNITARIO,NaN,NaN,NaN,NaN,NaN,3099,NaN,NaN,NaN,NaN,NaN,NaN
16,TOTAL,1059467.0,1053648.0,997358.0,984805.0,1029914.0,1052520,NaN,NaN,NaN,NaN,NaN,NaN